version: '2'
services:
  web:
      build: .
      ports:
       - "5000:5000"
      volumes:
       - .:/code
  redis:
      image: "redis:alpine"
  agent:
      image: "datadog/docker-dd-agent"
      environment:
          - API_KEY=your_api_key_here
