version: '3'
services:
  agent:
    image: "datadog/agent:latest"
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=TRUE
      # STEP 03 - Collect Logs
      # - DD_LOGS_ENABLED=true
      # - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      # STEP 03 - Collect Logs
      # - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
  redis:
    image: "redis:4.0.13-alpine"
  web:
    # STEP 03 - Collect Logs
    # labels:      
    #  com.datadoghq.ad.logs: '[{"source": "python", "service": "web"}]'
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    build: .
    command: flask run --port=5000 --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - "./app:/app"
    depends_on:
      - agent
      - redis
  taster:
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "taster"}]'
    environment:
      - FLASK_APP=taster.py
      - FLASK_DEBUG=1
    build: .
    command: flask run --port=5001 --host=0.0.0.0
    ports:
      - "5001:5001"
    volumes:
      - "./app:/app"
    depends_on:
      - agent
      - redis
