version: '3'
services:
  agent:
    image: "datadog/docker-dd-agent:latest"
    environment:
      - DD_API_KEY
    ports:
      - "8126:8126"
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - ./step01:/app
    depends_on:
      - agent
      - redis
  taster:
    build: .
    command: python taster.py
    ports:
      - "5001:5001"
    volumes:
      - ./step01:/app
    depends_on:
      - agent
      - redis
